// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbphltstuyzuqgpizlqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZicGhsdHN0dXl6dXFncGl6bHFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDY3MTksImV4cCI6MjA2MTQyMjcxOX0.VOWJxIsOb1iHrt-2LQOS1i7V2V62ScPCdaFKtH0m9p8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);